### ISSUE TITLE
Add support for es6 imports

### ISSUE THREAD

**Issue by ConnerAiken** [ElliotNB/nimbly#29]
It would be nice to support CommonJS/ES6 imports for the ObservableSlim and Nimbly libraries for transpiling/minification/bundling purposes.

Boilerplate repo: https://github.com/ConnerAiken/nimbly-boilerplate

The `master` branch is a working boilerplate.
The `es6-import` branch is an example of how I would expect the library to be imported using es6 modules.
The `es5-import` branch is an attempt at using CommonJS (require) for the libraries, but I get the error: `MutationObserver is not a constructor`

**Comment by ElliotNB** [comment]
Looked into this with Conner today -- does support ES6 imports but the dependency injection wrapper is required. Closing for now, but we probably should modify the Nimbly examples to show a working import.
